const crypto=require('crypto');
const {supabase}=require('../lib/db');
function secret(){return process.env.CUSTOMER_SESSION_SECRET||process.env.ADMIN_SESSION_SECRET||'change-me';}
function sign(v){return crypto.createHmac('sha256',secret()).update(v).digest('base64url');}
function cookie(payload){const p=Buffer.from(JSON.stringify(payload)).toString('base64url');return `${p}.${sign(p)}`;}
function read(req){const raw=req.headers.cookie||'';const m=raw.match(/(?:^|;\s*)amc_customer=([^;]+)/);if(!m)return null;try{const [p,s]=decodeURIComponent(m[1]).split('.');if(!p||!s||sign(p)!==s)return null;const x=JSON.parse(Buffer.from(p,'base64url').toString());return x.exp>Date.now()?x:null;}catch{return null;}}
function hash(password,salt=crypto.randomBytes(16).toString('hex')){const derived=crypto.scryptSync(password,salt,64).toString('hex');return `${salt}:${derived}`;}
function verify(password,stored){try{const [salt,key]=String(stored).split(':');const got=crypto.scryptSync(password,salt,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(got,'hex'),Buffer.from(key,'hex'));}catch{return false;}}
function setSession(res,id){res.setHeader('Set-Cookie',`amc_customer=${encodeURIComponent(cookie({id,exp:Date.now()+30*24*60*60*1000}))}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`);}
function clear(res){res.setHeader('Set-Cookie','amc_customer=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');}
module.exports=async(req,res)=>{try{
 const sess=read(req);
 if(req.method==='GET'){if(!sess)return res.status(401).json({error:'Not logged in'});const rows=await supabase(`customer_accounts?id=eq.${encodeURIComponent(sess.id)}&select=id,name,phone,email,address`);const c=rows&&rows[0];if(!c){clear(res);return res.status(401).json({error:'Account not found'});}if(req.query.orders==='1'){const os=await supabase(`orders?customer_account_id=eq.${encodeURIComponent(c.id)}&select=id,date,created_at,total,status,payment_status&order=created_at.desc`);return res.json({customer:c,orders:(os||[]).map(o=>({id:o.id,date:o.date,createdAt:o.created_at,total:Number(o.total||0),status:o.status,paymentStatus:o.payment_status}))});}return res.json({customer:c});}
 if(req.method==='DELETE'){clear(res);return res.json({ok:true});}
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const b=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});
 if(b.action==='register'){if(!b.name||!b.phone||!b.password||String(b.password).length<6)return res.status(400).json({error:'Name, phone and a 6+ character password are required'});const phone=String(b.phone).replace(/\D/g,'');const email=String(b.email||'').trim().toLowerCase();if(phone.length<8)return res.status(400).json({error:'Enter a valid phone number'});const existing=await supabase(`customer_accounts?or=(phone.eq.${encodeURIComponent(phone)},email.eq.${encodeURIComponent(email)})&select=id&limit=1`);if(existing&&existing.length)return res.status(409).json({error:'An account already exists for this phone or email'});const row={id:'CUS-'+crypto.randomUUID(),name:String(b.name).slice(0,120),phone,email,address:String(b.address||'').slice(0,500),password_hash:hash(String(b.password))};await supabase('customer_accounts',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(row)});setSession(res,row.id);return res.status(201).json({ok:true});}
 if(b.action==='login'){const identifier=String(b.identifier||'').trim(),email=identifier.toLowerCase(),phone=identifier.replace(/\D/g,'');let rows=[];if(email.includes('@'))rows=await supabase(`customer_accounts?email=eq.${encodeURIComponent(email)}&select=*&limit=1`);else rows=await supabase(`customer_accounts?phone=eq.${encodeURIComponent(phone)}&select=*&limit=1`);const c=rows&&rows[0];if(!c||!verify(String(b.password||''),c.password_hash))return res.status(401).json({error:'Invalid login details'});setSession(res,c.id);return res.json({ok:true});}
 return res.status(400).json({error:'Unknown action'});
}catch(e){return res.status(e.status||500).json({error:e.message,details:e.data||null});}};
