const { supabase } = require('../lib/db');
const { requireAdmin } = require('../lib/auth');
const { getSettings, sendEmail, emailEnabled } = require('../lib/gmail');
module.exports=async(req,res)=>{try{
 if(req.method==='GET'){if(req.query.admin==='1'){if(!requireAdmin(req,res))return;return res.json(await supabase('reviews?select=*&order=created_at.desc')||[]);}return res.json(await supabase('reviews?select=id,name,rating,review,date,status&status=eq.approved&order=created_at.desc')||[]);}
 if(req.method==='POST'){const b=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const rating=Math.min(5,Math.max(1,Number(b.rating)||5));if(!b.name||!b.review)return res.status(400).json({error:'Name and review are required'});const row={id:'REV-'+Date.now(),name:String(b.name),rating,review:String(b.review).slice(0,1000),date:new Date().toLocaleString(),status:'pending'};await supabase('reviews',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});
   try { const settings=await getSettings(); const to=String(settings?.gmail_admin_email||'').trim(); if(to&&emailEnabled(settings,'email_review')) await sendEmail({to,subject:`AMC Enterprises — New Customer Review`,text:`A new review is waiting for admin approval.\n\nName: ${row.name}\nRating: ${row.rating}/5\nReview: ${row.review}\nStatus: pending`,eventKey:`review:${row.id}`}); } catch(mailErr){console.warn('Gmail review notification failed:',mailErr.message);}
   return res.status(201).json({ok:true});}
 if(!requireAdmin(req,res))return;const id=encodeURIComponent(req.query.id||'');if(req.method==='PATCH'){const b=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const status=['pending','approved','rejected'].includes(b.status)?b.status:'pending';await supabase(`reviews?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status})});return res.json({ok:true});}if(req.method==='DELETE'){await supabase(`reviews?id=eq.${id}`,{method:'DELETE'});return res.json({ok:true});}return res.status(405).json({error:'Method not allowed'});
}catch(e){return res.status(e.status||500).json({error:e.message,details:e.data||null});}};
